packages:
  - 'packages/*'
  - 'apps/*'
allowBuilds:
  '@biomejs/biome': true
  '@parcel/watcher': true
  '@swc/core': true
  bufferutil: true
  es5-ext: true
  esbuild: true
  utf-8-validate: true
  vue-demi: true
